name: Build and Push WordPress Base Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'wordpress/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: agimon-llc/wordpress
  TAG: stg-latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./wordpress
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Display pushed image info
        run: echo "Image pushed to $REGISTRY/$IMAGE_NAME:$TAG"
